AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x

Resources:

  # Layers
  MGConnectorDependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mg-connector-dependencies
      Description: Dependencies for the Redwood MG Connector
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs10.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  # Lambda handlers
  ProcessMGFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/process-mg-file/
      FunctionName: process-mg-file
      Description: Function for processing a MercuryGate file
      Handler: index.handler
      Policies: 
        - S3ReadPolicy:
            BucketName: mg-connector-test-bucket
      Layers: 
        - Ref: MGConnectorDependencyLayer
      Environment: 
        Variables:
          S3_BUCKET: rw-mg-connector
